setps:
  # 1단계 (docker-compose -f docker-compose.prod.yaml build)
  - name: docker/compose:1.29.0
    args:
      - -f
      - deploy-test-backend/backend/docker-compose.prod.yaml
      - build

  # 2단계 (docker-compose -f docker-compose.prod.yaml push)
  - name: docker/compose:1.29.0
    args:
      - -f
      - deploy-test-backend/backend/docker-compose -f docker-compose.prod.yaml
      - push

  # 3단계 (kubectl set image deployment/mybackend my-backend03-sha256-1=asia.gcr.io/curious-sandbox-370715/my-backend03:8.0)
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deploy-test-backend/backend/deployment/mybackend
      - my-backend03-sha256-1=asia.gcr.io/curious-sandbox-370715/my-backend03:9.0
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1
