version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/curious-sandbox-370715/my-backend03:10.0
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./src:/myfolder/src
    # env_file:
    #   - ./.env.prod
    ports:
      - 3000:3000

  # my-database:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'mydocker03'
  #     MYSQL_ROOT_PASSWORD: '0000'
  #   ports:
  #     - 3306:3306
